language: android
jdk: oraclejdk8
sudo: required # false for Container-Based Infrastructure, required for Sudo-enabled Infrastructure
dist: trusty

env:
  global:
    - PROJECT_NAME= GearVRF
    - PROJECT_DIR=${TRAVIS_BUILD_DIR} # Project direct
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.3
    - android-25
  licenses:
    - android-sdk-license-.+
    - '.+'

before_script:
    - cd ${PROJECT_DIR}
    - echo "only_daydream=true" >> gradle.properties
      
script:
    - cd ${PROJECT_DIR} &&  ./gradlew assembleDebug
